# Generated by Django 6.0.6 on 2026-07-08 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goalschedule',
            name='reminder_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='goalschedule',
            name='reminder_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
