# Generated by Django 6.0.6 on 2026-07-03 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='goals.goal')),
            ],
            options={
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['goal', 'date'], name='checkin_goal_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('goal', 'date'), name='unique_goal_checkin_per_day')],
            },
        ),
    ]
